"""
Report Generator — Combines all test results into a unified HTML report.
"""

import os
import json
from datetime import datetime


SEVERITY_MAP = {
    'nikto': 'medium',
    'gobuster': 'info',
    'zap_passive': 'medium',
    'zap_active': 'high',
    'slowhttptest': 'high',
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Night — Nginx Security Test Report</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0f1117; color: #e2e8f0; margin: 0; padding: 0; }}
  header {{ background: #1a1f2e; padding: 32px 40px; border-bottom: 2px solid #334155; }}
  header h1 {{ margin: 0; font-size: 28px; color: #60a5fa; }}
  header .meta {{ color: #94a3b8; margin-top: 8px; font-size: 14px; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 32px 40px; }}
  .summary {{ display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin-bottom: 32px; }}
  .stat-card {{ background: #1e2536; border-radius: 8px; padding: 20px; text-align: center; border: 1px solid #334155; }}
  .stat-card .num {{ font-size: 36px; font-weight: bold; }}
  .stat-card .label {{ color: #94a3b8; font-size: 13px; margin-top: 4px; }}
  .high {{ color: #f87171; }} .medium {{ color: #fbbf24; }} .info {{ color: #60a5fa; }} .low {{ color: #34d399; }}
  .section {{ margin-bottom: 40px; }}
  .section h2 {{ color: #60a5fa; border-bottom: 1px solid #334155; padding-bottom: 8px; margin-bottom: 16px; }}
  .tool-result {{ background: #1e2536; border-radius: 8px; border: 1px solid #334155; margin-bottom: 16px; overflow: hidden; }}
  .tool-header {{ padding: 16px 20px; background: #252d3d; display: flex; justify-content: space-between; align-items: center; }}
  .tool-header .name {{ font-weight: bold; font-size: 16px; }}
  .tool-header .badge {{ padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; }}
  .badge-high {{ background: #7f1d1d; color: #fca5a5; }}
  .badge-medium {{ background: #78350f; color: #fcd34d; }}
  .badge-info {{ background: #1e3a5f; color: #93c5fd; }}
  .tool-body {{ padding: 16px 20px; }}
  .tool-body pre {{ background: #0f1117; padding: 12px; border-radius: 6px; overflow-x: auto;
                    font-size: 12px; color: #cbd5e1; border: 1px solid #1e293b; white-space: pre-wrap; max-height: 400px; overflow-y: auto; }}
  .meta-row {{ display: flex; gap: 24px; font-size: 13px; color: #94a3b8; margin-bottom: 12px; flex-wrap: wrap; }}
  .meta-row span {{ display: flex; align-items: center; gap: 4px; }}
  footer {{ text-align: center; padding: 24px; color: #475569; font-size: 13px; border-top: 1px solid #1e293b; margin-top: 40px; }}
</style>
</head>
<body>
<header>
  <h1>🔒 Night — Nginx Security Test Report</h1>
  <div class="meta">Target: <strong>{target}</strong> &nbsp;|&nbsp; Generated: <strong>{timestamp}</strong> &nbsp;|&nbsp; Tests run: <strong>{tool_count}</strong></div>
</header>
<div class="container">

<div class="summary">
  <div class="stat-card"><div class="num high">{high_count}</div><div class="label">High Severity</div></div>
  <div class="stat-card"><div class="num medium">{medium_count}</div><div class="label">Medium Severity</div></div>
  <div class="stat-card"><div class="num info">{info_count}</div><div class="label">Informational</div></div>
  <div class="stat-card"><div class="num low">{tool_count}</div><div class="label">Tools Run</div></div>
</div>

<div class="section">
<h2>Test Results</h2>
{tool_sections}
</div>

</div>
<footer>Generated by Night — Nginx Security CLI Tool &nbsp;|&nbsp; For authorized testing only</footer>
</body></html>
"""

TOOL_SECTION_TEMPLATE = """
<div class="tool-result">
  <div class="tool-header">
    <span class="name">🛠 {tool_display}</span>
    <span class="badge badge-{severity}">{severity_label}</span>
  </div>
  <div class="tool-body">
    <div class="meta-row">
      <span>🎯 Target: <strong>{target}</strong></span>
      <span>⏱ {timestamp}</span>
      {file_info}
    </div>
    <pre>{output_preview}</pre>
  </div>
</div>
"""

TOOL_NAMES = {
    'nikto': 'Nikto — Passive/Configuration Scan',
    'gobuster': 'Gobuster — Directory Discovery',
    'zap_passive': 'OWASP ZAP — Passive Scan',
    'zap_active': 'OWASP ZAP — Active Attack Scan',
    'slowhttptest': 'SlowHTTPTest — Slow HTTP DoS Simulation',
}


def _truncate(text, max_chars=3000):
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + f"\n\n... [truncated — see full report file] ..."


def _read_report_file(path):
    if not path or not os.path.exists(path):
        return ""
    try:
        with open(path, 'r', errors='replace') as f:
            return f.read()
    except Exception:
        return ""


def generate(results, target_url, output_dir):
    """
    Generate a unified HTML report from a list of tool result dicts.
    Returns path to generated report.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, f"night_report_{report_ts}.html")

    # Flatten results (some tools return lists)
    flat_results = []
    for r in results:
        if isinstance(r, list):
            flat_results.extend(r)
        elif r is not None:
            flat_results.append(r)

    tool_sections = ""
    high_count = medium_count = info_count = 0

    for result in flat_results:
        tool = result.get('tool', 'unknown')
        severity = SEVERITY_MAP.get(tool, 'info')
        if severity == 'high':
            high_count += 1
        elif severity == 'medium':
            medium_count += 1
        else:
            info_count += 1

        # Get output to display
        file_content = _read_report_file(result.get('output_file'))
        stdout = result.get('stdout', '')
        display_output = file_content or stdout or "(no output)"
        display_output = _truncate(display_output)

        file_info = ""
        if result.get('output_file'):
            file_info = f'<span>📄 <a href="file://{result["output_file"]}" style="color:#60a5fa">{os.path.basename(result["output_file"])}</a></span>'

        tool_sections += TOOL_SECTION_TEMPLATE.format(
            tool_display=TOOL_NAMES.get(tool, tool),
            severity=severity,
            severity_label=severity.upper(),
            target=result.get('target', target_url),
            timestamp=result.get('timestamp', ''),
            file_info=file_info,
            output_preview=display_output.replace('<', '&lt;').replace('>', '&gt;'),
        )

    html = HTML_TEMPLATE.format(
        target=target_url,
        timestamp=timestamp,
        tool_count=len(flat_results),
        high_count=high_count,
        medium_count=medium_count,
        info_count=info_count,
        tool_sections=tool_sections or "<p style='color:#94a3b8'>No test results to display.</p>",
    )

    with open(output_file, 'w') as f:
        f.write(html)

    return output_file