upstream cuckoo_web {
    server 127.0.0.1:9090;
}

server {
    listen 80;
    #server_tokens on;
    merge_slashes off;

    location /static {
        alias /opt/cuckoo3/static/;
        autoindex on;
    }

    location / {
        client_max_body_size 1G;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://cuckoo_web;
    }
}