user www-data;
worker_processes auto;
pid /run/nginx.pid;
#error_log /var/log/nginx/error.log;
error_log off;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
    server_tokens off;
    merge_slashes off;
    add_header Content-Security-Policy "default-src 'none'";

    server {
        listen 80;
        merge_slashes off;
        
        location / {
          return 302 https://example.com$uri;
        }

        # Alias traversal (Off-By-Slash)
        location /static {
            alias /var/www/static/;
        }

        # proxy_pass SSRF (Off-By-Slash)
        location /api {
            proxy_pass http://apiserver/v1/;
        }
        
        location /downloads/ {
            if ($http_cookie ~* "secret_user") {
                add_header X-Status "Special-User";
            }
            autoindex on;
        }
    }
}
