events {}

http {
    #server_tokens on;
    #error_log off;

    server {
        listen 80;
        
        # Alias traversal (Off-By-Slash)
        location /static {
            alias /var/www/static/;
        }

        # proxy_pass SSRF (Off-By-Slash)
        location /api {
            proxy_pass http://apiserver/v1/;
        }
        
        location /downloads/ {
            autoindex on;
        }
    }
}
