import subprocess
import shutil
from pathlib import Path
from rich.console import Console
from rich.table import Table
from rich import box


console = Console()


def _run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, capture_output=capture, text=True)


def _f2b_available() -> bool:
    return shutil.which("fail2ban-client") is not None


FILTERS: dict[str, str] = {
    "nginx-4xx": """\
[Definition]
# Catch 4xx responses (common scanner / bot footprint)
failregex = ^<HOST>.*"(GET|POST|HEAD).*" (400|401|403|404|444) .*$
ignoreregex = .*(robots.txt|favicon.ico|\\.jpg|\\.png|\\.css|\\.js)
""",

    "nginx-http-auth": """\
[Definition]
# Repeated HTTP Basic Auth failures
failregex = ^ \\[error\\] \\d+#\\d+: \\*\\d+ user "(?:[^"]+|.*?)"[:]? (password mismatch|was not found in "[^\\"]*"), client: <HOST>, server: \\S*, request: "\\S+ \\S+ HTTP/\\d+\\.\\d+", host: "\\S+"(?:, referrer: "\\S+")?\\s*$
ignoreregex =
datepattern = {^LN-BEG}
""",

    "nginx-botsearch": """\
[INCLUDES]
before = botsearch-common.conf

[Definition]
# Bots scanning for non-existent URLs
failregex = ^<HOST> \\- \\S+ \\[\\] "(GET|POST|HEAD) \\/<block> \\S+" 404 .+$
            ^ \\[error\\] \\d+#\\d+: \\*\\d+ (\\S+ )?"\\S+" (failed|is not found) \\(2\\: No such file or directory\\), client\\: <HOST>\\, server\\: \\S*\\, request: "(GET|POST|HEAD) \\/<block> \\S+"\\, .*?$
ignoreregex =
datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\\s*%%z)?
              ^[^\\[]*\\[({DATE})
              {^LN-BEG}
""",

    "nginx-forbidden": """\
[Definition]
# Directory listing / forbidden access attempts
failregex = directory index of .+ is forbidden, client: <HOST>, server: .+
ignoreregex =
""",

    "nginx-sslerror": """\
[Definition]
# Failed SSL/TLS handshakes (bad client, attacker probing)
failregex = SSL_do_handshake\\(\\) failed .+ while SSL handshaking, client: <HOST>, server: .+
ignoreregex =
datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\\s*%%z)?
              ^[^\\[]*\\[({DATE})
              {^LN-BEG}
""",

    "nginx-limit-req": """\
[Definition]
# IPs exceeding Nginx limit_req (potential DDoS / aggressive bot)
ngx_limit_req_zones = [^"]+
failregex = ^\\s*\\[[a-z]+\\] \\d+#\\d+: \\*\\d+ limiting requests, excess: [\\d\\.]+ by zone "(?:%(ngx_limit_req_zones)s)", client: <HOST>,
ignoreregex =
datepattern = {^LN-BEG}
""",
}

# TODO some problem with [ufw-probe] jail -> no ufw filter (create one)
CUSTOM_JAIL_CONF = """\
# /etc/fail2ban/jail.d/night-active-defense.conf
# Generated by NIGHT - Nginx Integrated Guard & Hardening Toolkit (do not edit manually).

[DEFAULT]
# How long an IP is banned (1 day default – aggressive)
bantime  = 1d
# Window in which maxretry failures trigger a ban
findtime = 1d
# IPs to never ban (loopback + private ranges)
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
# Maximum retries before ban
maxretry = 5
# Use UFW for banning
banaction = ufw
banaction_allports = ufw

# ── SSH ──────────────────────────────────────────────────────────────────────
[sshd]
enabled  = true
maxretry = 3

# ── Nginx – 4xx flood ────────────────────────────────────────────────────────
[nginx-4xx]
enabled  = true
port     = http,https
filter   = nginx-4xx
logpath  = /var/log/nginx/access.log
maxretry = 10
findtime = 600
bantime  = 3600

# ── Nginx – HTTP Auth brute-force ─────────────────────────────────────────────
[nginx-http-auth]
enabled  = true
port     = http,https
filter   = nginx-http-auth
logpath  = /var/log/nginx/error.log

# ── Nginx – bot / scanner ────────────────────────────────────────────────────
[nginx-botsearch]
enabled  = true
port     = http,https
filter   = nginx-botsearch
logpath  = /var/log/nginx/access.log

# ── Nginx – forbidden directories ─────────────────────────────────────────────
[nginx-forbidden]
enabled  = true
port     = http,https
filter   = nginx-forbidden
logpath  = /var/log/nginx/error.log

# ── Nginx – SSL errors ───────────────────────────────────────────────────────
[nginx-sslerror]
enabled  = true
port     = http,https
filter   = nginx-sslerror
logpath  = /var/log/nginx/error.log

# ── Nginx – rate-limit breaches ──────────────────────────────────────────────
[nginx-limit-req]
enabled  = true
port     = http,https
filter   = nginx-limit-req
logpath  = /var/log/nginx/error.log
maxretry = 10

# ── UFW log monitoring ───────────────────────────────────────────────────────
[ufw-probe]
enabled  = true
filter   = ufw
logpath  = /var/log/ufw.log
maxretry = 5
bantime  = 86400
"""

FILTER_DIR = Path("/etc/fail2ban/filter.d")
JAIL_DIR = Path("/etc/fail2ban/jail.d")
JAIL_FILE = JAIL_DIR / "night-active-defense.conf"


def install_filters() -> None:
    """Write all custom Nginx Fail2ban filters to /etc/fail2ban/filter.d/."""
    FILTER_DIR.mkdir(parents=True, exist_ok=True)

    for name, content in FILTERS.items():
        path = FILTER_DIR / f"{name}.conf"

        if path.exists():
            shutil.copy(path, f"{path}.night-backup")

        with open(path, "w") as f:
            f.write(content)
        console.print(f"[bold green][IPS] ✔ Filter written: {path}[/bold green]")


def install_jails(bantime: str = "1d", findtime: str = "1d", maxretry: int = 5) -> None:
    """
    Write the combined jail config and restart Fail2ban.

    Args:
        bantime:  How long to ban (e.g. '1d', '3600').
        findtime: Detection window (e.g. '1d', '600').
        maxretry: Number of failures before banning.
    """
    JAIL_DIR.mkdir(parents=True, exist_ok=True)

    conf = CUSTOM_JAIL_CONF.replace("bantime  = 1d", f"bantime  = {bantime}")
    conf = conf.replace("findtime = 1d", f"findtime = {findtime}")
    conf = conf.replace("maxretry = 5", f"maxretry = {maxretry}", 1)

    if JAIL_FILE.exists():
        shutil.copy(JAIL_FILE, f"{JAIL_FILE}.night-backup")

    with open(JAIL_FILE, "w") as f:
        f.write(conf)
    console.print(f"[bold green][IPS] ✔ Jail config written to {JAIL_FILE}[/bold green]")

    console.print("[cyan]Testing Fail2ban configuration...[/cyan]")
    test = _run(["fail2ban-server", "-t"], check=False, capture=True)
    if test.returncode != 0:
        console.print(f"[bold red][IPS] ✘ Fail2ban configuration test failed. Reverting changes.[/bold red]\n{test.stderr}")
        if Path(f"{JAIL_FILE}.night-backup").exists():
            shutil.move(f"{JAIL_FILE}.night-backup", JAIL_FILE)
        return

    _run(["systemctl", "restart", "fail2ban"])
    console.print("[bold green][IPS] ✔ Fail2ban restarted.[/bold green]")


def deploy(bantime: str = "1d", findtime: str = "1d", maxretry: int = 5) -> None:
    """Full deploy: install filters + jails + restart."""
    if not _f2b_available():
        console.print("[bold red][IPS] ✘ fail2ban-client not found. Run install_dependencies.sh first.[/bold red]")
        return
    install_filters()
    install_jails(bantime, findtime, maxretry)
    print_status()


def list_jails() -> list[str]:
    """Return the list of active Fail2ban jails."""
    if not _f2b_available():
        return []
    result = _run(["fail2ban-client", "status"], capture=True, check=False)
    for line in result.stdout.splitlines():
        if "Jail list:" in line:
            jails = line.split(":", 1)[1].strip()
            return [j.strip() for j in jails.split(",") if j.strip()]
    return []


def jail_status(jail: str) -> str:
    """Return the raw Fail2ban status for a specific jail."""
    result = _run(["fail2ban-client", "status", jail], capture=True, check=False)
    return result.stdout


def banned_ips() -> dict[str, list[str]]:
    """Return a dict mapping each jail -> list of banned IPs."""
    out: dict[str, list[str]] = {}
    for jail in list_jails():
        raw = jail_status(jail)
        for line in raw.splitlines():
            if "Banned IP list:" in line:
                ips_raw = line.split(":", 1)[1].strip()
                out[jail] = [ip for ip in ips_raw.split() if ip]
                break
        else:
            out[jail] = []
    return out


def unban_ip(ip: str) -> None:
    """Unban an IP address across all jails."""
    for jail in list_jails():
        _run(["fail2ban-client", "set", jail, "unbanip", ip], check=False)
    console.print(f"[bold green][IPS] ✔ Unbanned {ip} across all jails.[/bold green]")


def ban_ip(ip: str, jail: str = "nginx-4xx") -> None:
    """Manually ban an IP in a specific jail."""
    result = _run(["fail2ban-client", "set", jail, "banip", ip], check=False, capture=True)
    if result.returncode == 0:
        console.print(f"[bold green][IPS] ✔ Banned {ip} in jail '{jail}'.[/bold green]")
    else:
        console.print(f"[bold red][IPS] ✘ Failed to ban {ip}:[/bold red] {result.stderr.strip()}")


def print_status() -> None:
    result = _run(["fail2ban-client", "status"], capture=True, check=False)
    console.print(result.stdout)


def status() -> dict:
    available = _f2b_available()
    if not available:
        return {"available": False, "active": False, "jails": []}

    result = _run(["systemctl", "is-active", "fail2ban"], capture=True, check=False)
    active = result.stdout.strip() == "active"
    return {
        "available": available,
        "active": active,
        "jails": list_jails(),
    }


def run_interactive() -> None:
    console.print("\n[bold]╔════════════════════════════════════════╗[/bold]")
    console.print("[bold]║            IPS  (Fail2ban)             ║[/bold]")
    console.print("[bold]╚════════════════════════════════════════╝[/bold]\n")

    s = status()
    available_icon = "[green]✔[/green]" if s['available'] else "[red]✘[/red]"
    active_icon = "[green]✔[/green]" if s['active'] else "[red]✘[/red]"

    console.print(f"  fail2ban installed: {available_icon}")
    console.print(f"  fail2ban active   : {active_icon}")
    console.print(f"  fail2ban jails    : {', '.join(s['jails']) or 'none'}\n")

    try:
        console.print("  [1] Deploy full Fail2ban config (filters + jails)")
        console.print("  [2] Show banned IPs per jail")
        console.print("  [3] Unban an IP")
        console.print("  [4] Manually ban an IP")
        console.print("  [5] Show Fail2ban overall status")
        console.print("  \\[q] Back")
        choice = input("> ").strip()

        if choice == "1":
            bantime = input("  Ban duration [default: 1d]: ").strip() or "1d"
            findtime = input("  Detection window [default: 1d]: ").strip() or "1d"
            try:
                maxretry = int(input("  Max retries [default: 5]: ").strip() or "5")
            except ValueError:
                console.print("[yellow][!] Invalid integer. Defaulting to 5.[/yellow]")
                maxretry = 5
            deploy(bantime, findtime, maxretry)

        elif choice == "2":
            bans = banned_ips()
            table = Table(title="Currently Banned IPs", box=box.SIMPLE)
            table.add_column("Jail Name", style="cyan")
            table.add_column("Banned IPs", style="red")
            for jail, ips in bans.items():
                label = ", ".join(ips) if ips else "[dim](none)[/dim]"
                table.add_row(jail, label)
            console.print(table)

        elif choice == "3":
            ip = input("  IP to unban: ").strip()
            if ip: unban_ip(ip)

        elif choice == "4":
            ip = input("  IP to ban: ").strip()
            jail = input("  Jail [default: nginx-4xx]: ").strip() or "nginx-4xx"
            if ip: ban_ip(ip, jail)

        elif choice == "5":
            print_status()

        elif choice.lower() == "q":
            return
        else:
            console.print("[yellow]  Invalid choice.[/yellow]")
    except KeyboardInterrupt:
        pass