import subprocess
import shutil
import os
from pathlib import Path
from rich.console import Console


console = Console()


def _run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        check=check,
        capture_output=capture,
        text=True,
    )


def _nginx_reload() -> bool:
    """Test nginx config, then reload. Returns True on success."""
    test = _run(["nginx", "-t"], check=False, capture=True)
    if test.returncode != 0:
        console.print(f"[bold red][TLS] ✘ nginx -t failed:\n{test.stderr}[/bold red]")
        return False
    _run(["systemctl", "reload", "nginx"])
    console.print("[bold green][TLS] ✔ Nginx reloaded.[/bold green]")
    return True


HARDENED_SSL_SNIPPET = """\
# Hardened SSL (generated by NIGHT - Nginx Integrated Guard & Hardening Toolkit)
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_stapling on;
ssl_stapling_verify on;

# HSTS – starts at 30 days; increase max-age after verifying everything works
add_header Strict-Transport-Security "max-age=2592000; includeSubDomains" always;
add_header X-Frame-Options DENY always;
add_header X-Content-Type-Options nosniff always;
add_header Referrer-Policy "no-referrer-when-downgrade" always;
"""

REDIRECT_SERVER_BLOCK = """\
# HTTP → HTTPS redirect (generated by NIGHT - Nginx Integrated Guard & Hardening Toolkit)
server {{
    listen 80;
    listen[::]:80;
    server_name {domains};
    return 301 https://$host$request_uri;
}}
"""


def _write_ssl_snippet(snippet_path: str = "/etc/nginx/snippets/ssl-hardened.conf") -> None:
    Path(snippet_path).parent.mkdir(parents=True, exist_ok=True)

    if os.path.exists(snippet_path):
        shutil.copy(snippet_path, f"{snippet_path}.bak")
        console.print(f"[dim]Backed up existing snippet to {snippet_path}.bak[/dim]")

    with open(snippet_path, "w") as f:
        f.write(HARDENED_SSL_SNIPPET)
    console.print(f"[bold green][TLS] ✔ Hardened SSL snippet written to {snippet_path}[/bold green]")


def check_certbot() -> bool:
    """Return True if certbot is available."""
    return shutil.which("certbot") is not None


def obtain_certificate(domains: list[str], email: str, webroot: bool = False, webroot_path: str = "/var/www/html") -> bool:
    """
        Obtain a Let's Encrypt certificate via Certbot.

        Args:
            domains:      List of domain names, e.g. ['example.com', 'www.example.com']
            email:        Admin e-mail for expiry notifications.
            webroot:      Use --webroot authenticator instead of --nginx.
            webroot_path: Only relevant when webroot=True.

        Returns:
            True on success, False on failure.
    """
    if not check_certbot():
        console.print("[bold red][TLS] ✘ certbot not found. Run install_dependencies.sh first.[/bold red]")
        return False

    domain_flags = []
    for d in domains:
        domain_flags += ["-d", d]

    if webroot:
        cmd = [
                  "certbot", "certonly", "--webroot",
                  "-w", webroot_path,
                  "--email", email,
                  "--agree-tos", "--no-eff-email",
                  "--non-interactive",
              ] + domain_flags
    else:
        cmd = [
                  "certbot", "--nginx",
                  "--email", email,
                  "--agree-tos", "--no-eff-email",
                  "--non-interactive",
                  "--redirect",
              ] + domain_flags

    console.print(f"[cyan][TLS] Running certbot for: {', '.join(domains)}...[/cyan]")
    result = _run(cmd, check=False)
    if result.returncode != 0:
        console.print("[bold red][TLS] ✘ certbot failed (see terminal output).[/bold red]")
        return False

    console.print("[bold green][TLS] ✔ Certificate obtained.[/bold green]")
    return True


def harden_nginx_ssl(domain: str, cert_path: str | None = None, key_path: str | None = None, config_file: str | None = None) -> bool:
    cert = cert_path or f"/etc/letsencrypt/live/{domain}/fullchain.pem"
    key = key_path or f"/etc/letsencrypt/live/{domain}/privkey.pem"
    out = config_file or f"/etc/nginx/sites-available/{domain}"

    _write_ssl_snippet()

    server_block = f"""\
# Generated by NIGHT - Nginx Integrated Guard & Hardening Toolkit (TLS hardening)
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    ssl_certificate {cert};
    ssl_certificate_key {key};

    include snippets/ssl-hardened.conf;

    # --- your existing location blocks below ---
    location / {{
        # adjust root / proxy_pass as needed
        root /var/www/html;
        index index.html;
    }}
}}

{REDIRECT_SERVER_BLOCK.format(domains=domain)}
"""
    if os.path.exists(out):
        shutil.copy(out, f"{out}.night-backup")
        console.print(f"[yellow][!] Existing server block found. Backed up to {out}.night-backup[/yellow]")

    with open(out, "w") as f:
        f.write(server_block)
    console.print(f"[bold green][TLS] ✔ Hardened server block written to {out}[/bold green]")

    # Symlink into sites-enabled
    enabled = f"/etc/nginx/sites-enabled/{domain}"
    if os.path.lexists(enabled):
        os.unlink(enabled)

    os.symlink(out, enabled)
    console.print(f"[bold green]✔ Symlinked to {enabled}[/bold green]")

    return _nginx_reload()


def verify_renewal() -> None:
    """Run a certbot dry-run renewal and report the result."""
    console.print("[cyan][TLS] Running certbot renew --dry-run ...[/cyan]")
    result = _run(["certbot", "renew", "--dry-run"], check=False)
    if result.returncode == 0:
        console.print("[bold green][TLS] ✔ Renewal dry-run passed.[/bold green]")
    else:
        # TODO output relevant certbot logs
        console.print("[bold red][TLS] ✘ Renewal dry-run failed – check certbot logs.[/bold red]")


def status() -> dict:
    """Return a dict with the TLS status summary."""
    has_certbot = check_certbot()
    certs = []

    le_live = Path("/etc/letsencrypt/live")
    if le_live.exists():
        certs = [d.name for d in le_live.iterdir() if d.is_dir()]

    snippet_ok = Path("/etc/nginx/snippets/ssl-hardened.conf").exists()

    return {
        "certbot_installed": has_certbot,
        "certificates": certs,
        "hardened_snippet": snippet_ok,
    }


def run_interactive() -> None:
    console.print("\n[bold]╔══════════════════════════════════╗[/bold]")
    console.print("[bold]║ TLS Hardening  (Certbot + Nginx) ║[/bold]")
    console.print("[bold]╚══════════════════════════════════╝[/bold]\n")

    s = status()
    cert_icon = "[green]✔[/green]" if s['certbot_installed'] else "[red]✘[/red]"
    snip_icon = "[green]✔[/green]" if s['hardened_snippet'] else "[red]✘[/red]"

    console.print(f"  certbot installed : {cert_icon}")
    console.print(f"  existing certs    : {', '.join(s['certificates']) or 'none'}")
    console.print(f"  hardened snippet  : {snip_icon}\n")

    try:
        choice = input(
            "  [1] Obtain new certificate  [2] Harden existing Nginx block  [3] Verify renewal  \\[q] Back\n> ").strip()

        if choice == "1":
            raw = input("  Domains (comma-separated): ").strip()
            email = input("  Admin e-mail: ").strip()
            domains = [d.strip() for d in raw.split(",") if d.strip()]
            obtain_certificate(domains, email)

        elif choice == "2":
            domain = input("  Primary domain: ").strip()
            harden_nginx_ssl(domain)

        elif choice == "3":
            verify_renewal()

        elif choice.lower() == "q":
            return
        else:
            console.print("[yellow]  Invalid choice.[/yellow]")
    except KeyboardInterrupt:
        pass