import subprocess
import shutil
import os
from rich.console import Console


console = Console()


def _run(cmd: list[str], check: bool = True, capture: bool = False,
         input_text: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        check=check,
        capture_output=capture,
        text=True,
        input=input_text,
    )


def _ufw_available() -> bool:
    return shutil.which("ufw") is not None


def _nft_available() -> bool:
    return shutil.which("nft") is not None


class UFWManager:
    DEFAULT_RULES = [
        ("allow", "80/tcp",  "HTTP inbound"),
        ("allow", "443/tcp", "HTTPS inbound"),
    ]

    def reset_and_apply_defaults(self, allow_ssh: bool = True, ssh_subnet: str | None = None) -> None:
        """
            Reset UFW and apply a minimal deny-all + allow-needed ruleset.

            Args:
                allow_ssh:   Whether to allow SSH (port 22).
                ssh_subnet:  Restrict SSH to this CIDR, e.g. '192.168.1.0/24'.
                             None means allow from anywhere (less safe).
        """
        if not _ufw_available():
            console.print("[bold red][Firewall] ✘ ufw not found. Run install_dependencies.sh first.[/bold red]")
            return

        console.print("[cyan][Firewall] Resetting UFW rules ...[/cyan]")
        _run(["ufw", "--force", "reset"])

        _run(["ufw", "default", "deny", "incoming"])
        _run(["ufw", "default", "allow", "outgoing"])
        console.print("[bold green][Firewall] ✔ Defaults: deny incoming, allow outgoing.[/bold green]")

        # HTTP / HTTPS
        for action, port, label in self.DEFAULT_RULES:
            _run(["ufw", action, port])
            console.print(f"[bold green][Firewall] ✔ {action} {port}  ({label})[/bold green]")

        # SSH
        if allow_ssh:
            if ssh_subnet:
                _run(["ufw", "allow", "from", ssh_subnet, "to", "any",
                      "port", "22", "proto", "tcp"])
                console.print(f"[bold green][Firewall] ✔ SSH allowed from subnet {ssh_subnet}[/bold green]")
            else:
                _run(["ufw", "limit", "22/tcp"])
                console.print("[bold green][Firewall] ✔ SSH rate-limited (6 connections / 30 seconds).[/bold green]")

        # DNS out (for cert renewal, package updates, etc.)
        _run(["ufw", "allow", "out", "53/udp"])
        console.print("[bold green][Firewall] ✔ DNS (outgoing UDP 53) allowed.[/bold green]")

        # Enable
        _run(["ufw", "--force", "enable"])
        console.print("[bold green][Firewall] ✔ UFW enabled.[/bold green]")
        self.print_status()

    def add_rule(self, direction: str, port: str, proto: str = "tcp", from_ip: str | None = None) -> None:
        """
            Add a single UFW rule.

            Args:
                direction: 'allow' | 'deny' | 'limit'
                port:      Port number or service name, e.g. '8080'
                proto:     'tcp' | 'udp'
                from_ip:   Source CIDR to restrict the rule to (optional).
        """
        if not _ufw_available():
            console.print("[bold red][Firewall] ✘ ufw not found.[/bold red]")
            return

        if from_ip:
            cmd = ["ufw", direction, "from", from_ip, "to", "any", "port", port, "proto", proto]
        else:
            cmd = ["ufw", direction, f"{port}/{proto}"]

        _run(cmd)
        console.print(f"[bold green][Firewall] ✔ Rule added: {direction} {port}/{proto}[/bold green]"
              + (f"[bold green] from {from_ip}[/bold green]" if from_ip else ""))

    def delete_rule(self, rule_number: int) -> None:
        _run(["ufw", "--force", "delete", str(rule_number)])
        console.print(f"[bold green][Firewall] ✔ Rule #{rule_number} deleted.[/bold green]")

    def enable(self) -> None:
        _run(["ufw", "--force", "enable"])
        console.print("[bold green][Firewall] ✔ UFW enabled.[/bold green]")

    def disable(self) -> None:
        _run(["ufw", "disable"])
        console.print("[bold green][Firewall] ✔ UFW disabled.[/bold green]")

    def print_status(self) -> None:
        result = _run(["ufw", "status", "verbose"], capture=True, check=False)
        console.print(result.stdout)

    def status(self) -> dict:
        result = _run(["ufw", "status"], capture=True, check=False)
        active = "active" in result.stdout.lower()
        return {
            "available": _ufw_available(),
            "active": active,
            "raw": result.stdout.strip(),
        }


NFT_BASE_RULESET = """\
#!/usr/sbin/nft -f
# nftables base ruleset (generated by NIGHT - Nginx Integrated Guard & Hardening Toolkit)
# WARNING: Do not run simultaneously with UFW to avoid conflicts - This is a complementary layer alongside UFW.

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # Allow established / related connections
        ct state established,related accept

        # Loopback
        iif lo accept

        # ICMP (ping) – limit to avoid flood
        ip protocol icmp limit rate 5/second accept
        ip6 nexthdr icmpv6 limit rate 5/second accept

        # HTTP / HTTPS
        tcp dport { 80, 443 } accept

        # SSH (rate-limit new connections)
        tcp dport 22 ct state new limit rate 6/minute accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
"""

NFT_CONF_PATH = "/etc/nftables.conf"


class NftablesManager:
    """Manages a base nftables ruleset."""

    def write_base_ruleset(self, ssh_only_subnet: str | None = None) -> None:
        """
            Write the base nftables ruleset and enable the nftables service.

            Args:
                ssh_only_subnet: If set, restrict SSH to this CIDR in nftables.
        """
        if not _nft_available():
            console.print("[bold red][Firewall] ✘ nft not found. Run install_dependencies.sh first.[/bold red]")
            return

        ruleset = NFT_BASE_RULESET
        if ssh_only_subnet:
            # Replace the blanket SSH accept with a subnet-restricted one
            ruleset = ruleset.replace(
                "tcp dport 22 ct state new limit rate 6/minute accept",
                f"ip saddr {ssh_only_subnet} tcp dport 22 ct state new limit rate 6/minute accept",
            )

        if os.path.exists(NFT_CONF_PATH):
            shutil.copy(NFT_CONF_PATH, f"{NFT_CONF_PATH}.night-backup")
            console.print(f"[yellow]! Existing config backed up to {NFT_CONF_PATH}.night-backup[/yellow]")

        with open(NFT_CONF_PATH, "w") as f:
            f.write(ruleset)
        console.print(f"[bold green][Firewall] ✔ Ruleset written to {NFT_CONF_PATH}[/bold green]")

        _run(["systemctl", "enable", "nftables"])
        _run(["systemctl", "restart", "nftables"])
        console.print("[bold green][Firewall] ✔ nftables service enabled and started.[/bold green]")

    def reload(self) -> None:
        _run(["nft", "-f", NFT_CONF_PATH])
        console.print("[bold green][Firewall] ✔ Ruleset reloaded.[/bold green]")

    def show(self) -> None:
        result = _run(["nft", "list", "ruleset"], capture=True, check=False)
        console.print(result.stdout)

    def status(self) -> dict:
        result = _run(["systemctl", "is-active", "nftables"], capture=True, check=False)
        return {
            "available": _nft_available(),
            "service_active": result.stdout.strip() == "active",
        }


def status() -> dict:
    ufw = UFWManager().status()
    nft = NftablesManager().status()
    return {"ufw": ufw, "nftables": nft}


def run_interactive() -> None:
    ufw = UFWManager()
    nft = NftablesManager()

    console.print("\n[bold]╔══════════════════════════════════╗[/bold]")
    console.print("[bold]║    Firewall  (UFW + nftables)    ║[/bold]")
    console.print("[bold]╚══════════════════════════════════╝[/bold]\n")

    s = status()
    ufw_av_icon = "[green]✔[/green]" if s['ufw']['available'] else "[red]✘[/red]"
    ufw_ac_icon = "[green]✔[/green]" if s['ufw']['active'] else "[red]✘[/red]"
    nft_av_icon = "[green]✔[/green]" if s['nftables']['available'] else "[red]✘[/red]"
    nft_ac_icon = "[green]✔[/green]" if s['nftables']['service_active'] else "[red]✘[/red]"

    console.print(f"  UFW available     : {ufw_av_icon}")
    console.print(f"  UFW active        : {ufw_ac_icon}")
    console.print(f"  nftables available: {nft_av_icon}")
    console.print(f"  nftables active   : {nft_ac_icon}\n")

    if s['ufw']['active'] and s['nftables']['service_active']:
        console.print("[bold red]  [WARNING] Both UFW and raw nftables services are active![/bold red]")
        console.print("[bold red]  This can cause severe packet routing conflicts.[/bold red]\n")

        while True:
            try:
                console.print("[yellow]  Pick one to disable:[/yellow]")
                choice = input("  [1] UFW  [2] raw nftables  \\[q] Abort to menu\n> ").strip().lower()

                if choice == "1":
                    ufw.disable()
                    break
                elif choice == "2":
                    _run(["systemctl", "disable", "--now", "nftables"])
                    console.print("[bold green][Firewall] ✔ nftables service stopped and disabled.[/bold green]")
                    break
                elif choice == "q":
                    return
                else:
                    console.print("[yellow]  Invalid option.[/yellow]")
            except KeyboardInterrupt:
                console.print("\n[yellow][!] Operation cancelled by user. Returning to main menu.[/yellow]")
                return

    try:
        console.print("  [1] Apply default UFW ruleset (deny-all + HTTP/HTTPS/SSH)")
        console.print("  [2] Add custom UFW rule")
        console.print("  [3] Show UFW status")
        console.print("  [4] Apply base nftables ruleset")
        console.print("  [5] Show nftables ruleset")
        console.print("  \\[q] Back")
        choice = input("> ").strip()

        if choice == "1":
            ssh_sub = input("  Restrict SSH to subnet? (leave blank for rate-limited any): ").strip() or None
            ufw.reset_and_apply_defaults(allow_ssh=True, ssh_subnet=ssh_sub or None)

        elif choice == "2":
            direction = input("  Direction [allow/deny/limit]: ").strip()
            port = input("  Port: ").strip()
            proto = input("  Protocol [tcp/udp, default tcp]: ").strip() or "tcp"
            from_ip = input("  Source IP/CIDR (blank = any): ").strip() or None
            ufw.add_rule(direction, port, proto, from_ip)

        elif choice == "3":
            ufw.print_status()

        elif choice == "4":
            ssh_sub = input("  Restrict SSH to subnet in nftables? (blank = any): ").strip() or None
            nft.write_base_ruleset(ssh_sub or None)

        elif choice == "5":
            nft.show()

        elif choice.lower() == "q":
            return
        else:
            console.print("[yellow]  Invalid choice.[/yellow]")
    except KeyboardInterrupt:
        pass