import subprocess
import shutil
import os
import re
from pathlib import Path
from rich.console import Console


console = Console()


MODSEC_DIR       = Path("/etc/nginx/modsec")
MODSEC_CONF      = MODSEC_DIR / "modsecurity.conf"
MODSEC_MAIN      = MODSEC_DIR / "main.conf"
MODSEC_CUSTOM    = MODSEC_DIR / "custom-rules.conf"
CRS_PATH         = Path("/etc/nginx/owasp-crs")
NGINX_MODULE_SO  = Path("/usr/lib/nginx/modules/ngx_http_modsecurity_module.so")
AUDIT_LOG        = Path("/var/log/modsec_audit.log")


def _run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, capture_output=capture, text=True)


def _nginx_reload() -> bool:
    test = _run(["nginx", "-t"], check=False, capture=True)
    if test.returncode != 0:
        console.print(f"[bold red][WAF] ✘ nginx -t failed:\n{test.stderr}[/bold red]")
        return False
    _run(["systemctl", "reload", "nginx"])
    console.print("[bold green][WAF] ✔ Nginx reloaded.[/bold green]")
    return True


def _safe_backup(path: Path) -> None:
    if path.exists():
        backup_path = path.with_name(f"{path.name}.night-backup")
        shutil.copy(path, backup_path)
        console.print(f"[dim]  (Backed up {path.name} to .night-backup)[/dim]")


def _patch_file_line(path: Path, pattern: str, replacement: str) -> bool:
    """Find the first line matching pattern and replace it."""
    if not path.exists():
        return False

    text = path.read_text()
    new_text, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count:
        _safe_backup(path)
        path.write_text(new_text)
        return True
    return False


class ModSecurityManager:
    """Manages ModSecurity v3 installation and configuration for Nginx."""

    def is_lib_installed(self) -> bool:
        return Path("/usr/local/modsecurity/lib/libmodsecurity.so").exists()

    def is_module_installed(self) -> bool:
        candidates = [
            Path("/usr/lib/nginx/modules/ngx_http_modsecurity_module.so"),
            Path("/etc/nginx/modules/ngx_http_modsecurity_module.so"),
            Path("/usr/share/nginx/modules/ngx_http_modsecurity_module.so"),
        ]
        return any(p.exists() for p in candidates)

    def is_crs_installed(self) -> bool:
        return (CRS_PATH / "crs-setup.conf").exists()

    def set_engine_mode(self, mode: str) -> bool:
        """Set SecRuleEngine mode in modsecurity.conf."""
        if not MODSEC_CONF.exists():
            console.print(f"[bold red][WAF] ✘ {MODSEC_CONF} not found. Run install_deps.sh first.[/bold red]")
            return False

        valid = {"On", "DetectionOnly", "Off"}
        if mode not in valid:
            console.print(f"[bold red][WAF] ✘ Invalid mode '{mode}'. Must be one of {valid}[/bold red]")
            return False

        # Try to replace existing SecRuleEngine line
        patched = _patch_file_line(
            MODSEC_CONF,
            r"^SecRuleEngine\s+\S+",
            f"SecRuleEngine {mode}",
        )
        if not patched:
            # Append if not found
            with open(MODSEC_CONF, "a") as f:
                f.write(f"\nSecRuleEngine {mode}\n")

        console.print(f"[bold green][WAF] ✔ SecRuleEngine set to '{mode}'.[/bold green]")
        return _nginx_reload()

    def write_main_conf(self) -> None:
        """Write /etc/nginx/modsec/main.conf that includes the base config + CRS."""
        MODSEC_DIR.mkdir(parents=True, exist_ok=True)
        content = f"""\
# ModSecurity main config – generated by active-defense CLI
Include {MODSEC_CONF}
Include {CRS_PATH}/crs-setup.conf
Include {CRS_PATH}/rules/*.conf
"""
        if MODSEC_CUSTOM.exists():
            content += f"Include {MODSEC_CUSTOM}\n"

        _safe_backup(MODSEC_MAIN)
        MODSEC_MAIN.write_text(content)
        console.print(f"[bold green][WAF] ✔ main.conf written to {MODSEC_MAIN}[/bold green]")

    def set_crs_paranoia_level(self, level: int) -> bool:
        """Set the OWASP CRS paranoia level (1–4)."""
        if not (1 <= level <= 4):
            console.print("[bold red][WAF] ✘ Paranoia level must be 1–4.[/bold red]")
            return False

        setup = CRS_PATH / "crs-setup.conf"
        if not setup.exists():
            console.print("[bold red][WAF] ✘ crs-setup.conf not found. Install OWASP CRS first.[/bold red]")
            return False

        # TODO auto-patching doesnt work
        patched = _patch_file_line(
            setup,
            r"^#?setvar:'tx\.paranoia_level=\d'",
            f"setvar:'tx.paranoia_level={level}'",
        )
        if not patched:
            # Simpler modern CRS syntax
            patched = _patch_file_line(
                setup,
                r"^#?SecAction.*paranoia_level.*$",
                f'SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level={level}"',
            )

        if patched:
            console.print(f"[bold green][WAF] ✔ CRS paranoia level set to {level}.[/bold green]")
        else:
            console.print(f"[yellow][WAF] [i] Could not auto-patch crs-setup.conf. Set tx.paranoia_level manually.[/yellow]")
        return True

    def enable_in_nginx(self, server_config_path: str | None = None) -> bool:
        """Inject modsecurity directives into an Nginx server block."""
        cfg = Path(server_config_path or "/etc/nginx/sites-available/default")
        if not cfg.exists():
            console.print(f"[bold red][WAF] ✘ {cfg} not found.[/bold red]")
            return False

        text = cfg.read_text()
        if "modsecurity on;" in text:
            console.print("[bold green][WAF] ✔ modsecurity already enabled in this config.[/bold green]")
            return True

        console.print(f"[yellow][WAF] [!] Warning: Injecting WAF into the FIRST server block found in {cfg.name}[/yellow]")

        modsec_block = (
            "\n    # ModSecurity WAF\n"
            "    modsecurity on;\n"
            f"    modsecurity_rules_file {MODSEC_MAIN};\n"
        )
        patched = re.sub(
            r"(server_name\s+[^;]+;)",
            r"\1" + modsec_block,
            text,
            count=1,
        )
        if patched == text:
            # Fallback: insert after first `listen` directive
            patched = re.sub(
                r"(listen\s+[^;]+;)",
                r"\1" + modsec_block,
                text,
                count=1,
            )

        _safe_backup(cfg)
        cfg.write_text(patched)
        console.print(f"[bold green][WAF] ✔ modsecurity directives injected into {cfg}[/bold green]")
        return _nginx_reload()

    def add_custom_rule(self, rule: str) -> None:
        """Append a raw SecRule line to the custom rules file."""
        MODSEC_DIR.mkdir(parents=True, exist_ok=True)
        _safe_backup(MODSEC_CUSTOM)
        with open(MODSEC_CUSTOM, "a") as f:
            f.write(rule.strip() + "\n")
        console.print(f"[bold green][WAF] ✔ Rule appended to {MODSEC_CUSTOM}[/bold green]")

    def list_custom_rules(self) -> list[str]:
        if not MODSEC_CUSTOM.exists():
            return []
        return [line for line in MODSEC_CUSTOM.read_text().splitlines()
                if line.strip() and not line.startswith("#")]

    def tail_audit_log(self, lines: int = 30) -> None:
        if not AUDIT_LOG.exists():
            console.print(f"[yellow][WAF] [i] Audit log not found at {AUDIT_LOG}.[/yellow]")
            return
        result = _run(["tail", "-n", str(lines), str(AUDIT_LOG)], capture=True, check=False)
        console.print(result.stdout)

    def get_blocked_count(self) -> int:
        """Rough count of blocked requests in the audit log."""
        if not AUDIT_LOG.exists():
            return 0
        result = _run(["grep", "-c", "ModSecurity: Access denied", str(AUDIT_LOG)], capture=True, check=False)
        try:
            return int(result.stdout.strip())
        except ValueError:
            return 0

    def deploy(self, engine_mode: str = "DetectionOnly", paranoia_level: int = 1, nginx_config: str | None = None) -> None:
        """
            Full WAF deployment.

            1. Write main.conf
            2. Set engine mode
            3. Set CRS paranoia level
            4. Inject directives into Nginx config
        """
        if not self.is_lib_installed():
            console.print("[bold red][WAF] ✘ libmodsecurity not found. Run install_deps.sh first.[/bold red]")
            return
        if not self.is_module_installed():
            console.print("[bold red][WAF] ✘ Nginx ModSecurity module not found. Run install_deps.sh first.[/bold red]")
            return
        if not self.is_crs_installed():
            console.print("[bold red][WAF] ✘ OWASP CRS not found. Run install_deps.sh first.[/bold red]")
            return

        self.write_main_conf()
        self.set_engine_mode(engine_mode)
        self.set_crs_paranoia_level(paranoia_level)
        self.enable_in_nginx(nginx_config)
        console.print("\n[bold green][WAF] ✔ Deployment complete.[/bold green]")
        console.print(f"[bold]      Engine mode   : {engine_mode}[/bold]")
        console.print(f"[bold]      Paranoia level: {paranoia_level}[/bold]")
        console.print(f"[bold]      Audit log     : {AUDIT_LOG}[/bold]")

    def status(self) -> dict:
        engine_mode = "unknown"
        if MODSEC_CONF.exists():
            for line in MODSEC_CONF.read_text().splitlines():
                m = re.match(r"SecRuleEngine\s+(\S+)", line.strip())
                if m:
                    engine_mode = m.group(1)
                    break

        return {
            "lib_installed": self.is_lib_installed(),
            "module_installed": self.is_module_installed(),
            "crs_installed": self.is_crs_installed(),
            "engine_mode": engine_mode,
            "main_conf_exists": MODSEC_MAIN.exists(),
            "custom_rules": len(self.list_custom_rules()),
            "blocked_count": self.get_blocked_count(),
        }


_mgr = ModSecurityManager()


def status() -> dict:
    return _mgr.status()


def run_interactive() -> None:
    console.print("\n[bold]╔════════════════════════════════════════╗[/bold]")
    console.print("[bold]║      WAF (ModSecurity + OWASP CRS)     ║[/bold]")
    console.print("[bold]╚════════════════════════════════════════╝[/bold]\n")

    s = _mgr.status()
    libmodsec_icon = "[green]✔[/green]" if s['lib_installed'] else "[red]✘[/red]"
    nginx_mod_icon = "[green]✔[/green]" if s['module_installed'] else "[red]✘[/red]"
    crs_icon = "[green]✔[/green]" if s['crs_installed'] else "[red]✘[/red]"
    main_conf_icon = "[green]✔[/green]" if s['main_conf_exists'] else "[red]✘[/red]"

    console.print(f"  libmodsecurity    : {libmodsec_icon}")
    console.print(f"  Nginx module      : {nginx_mod_icon}")
    console.print(f"  OWASP CRS         : {crs_icon}")
    console.print(f"  Engine mode       : {s['engine_mode']}")
    console.print(f"  main.conf         : {main_conf_icon}")
    console.print(f"  Custom rules      : {s['custom_rules']}")
    console.print(f"  Blocked (log)     : {s['blocked_count']}\n")

    try:
        console.print("  [1] Full deploy (detection-only mode, paranoia 1)")
        console.print("  [2] Switch engine mode (On / DetectionOnly / Off)")
        console.print("  [3] Set CRS paranoia level (1–4)")
        console.print("  [4] Enable ModSecurity in a specific Nginx site config")
        console.print("  [5] Add a custom SecRule")
        console.print("  [6] List custom rules")
        console.print("  [7] Tail audit log")
        console.print("  \\[q] Back")
        choice = input("> ").strip()

        if choice == "1":
            _mgr.deploy()

        elif choice == "2":
            mode = input("  Mode [On/DetectionOnly/Off]: ").strip()
            _mgr.set_engine_mode(mode)

        elif choice == "3":
            try:
                level = int(input("  Paranoia level [1-4]: ").strip())
                _mgr.set_crs_paranoia_level(level)
            except ValueError:
                console.print("[yellow][!] Invalid integer.[/yellow]")

        elif choice == "4":
            path = input("  Path to Nginx site config [blank = /etc/nginx/sites-available/default]: ").strip() or None
            _mgr.enable_in_nginx(path)

        elif choice == "5":
            console.print('  Enter the full SecRule line, e.g.:')
            console.print('  SecRule REMOTE_ADDR "@ipMatch 1.2.3.4" "id:9001,phase:1,deny,status:403,msg:\'Blocked\'"')
            rule = input("  > ").strip()
            if rule:
                _mgr.add_custom_rule(rule)

        elif choice == "6":
            rules = _mgr.list_custom_rules()
            if rules:
                for r in rules:
                    console.print(f"  {r}")
            else:
                console.print("[dim]  (no custom rules yet)[/dim]")

        elif choice == "7":
            try:
                n = int(input("  Lines to show [default 30]: ").strip() or "30")
            except ValueError:
                console.print("[yellow][!] Invalid integer. Defaulting to 30.[/yellow]")
                n = 30
            _mgr.tail_audit_log(n)

        elif choice.lower() == "q":
            return
        else:
            console.print("[yellow]  Invalid choice.[/yellow]")
    except KeyboardInterrupt:
        pass